export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import User from '../(components)/User/page'
import './globals.css'
import { getUser } from '../(components)/Header'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user= getUser()
  return (
    <html lang="en">
      <body className=" h-screen bg-gradient-to-tr text-center from-orange-400 via-orange-900 to-orange-800">
        <div className=' bg-gradient-to-tr from-slate-800/40 to-slate-400/50'><div><User user={user} /></div></div>
        {children}
        </body>
    </html>
  )
}
