export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=" h-screen bg-gradient-to-tr text-center from-orange-400 via-orange-900 to-orange-800">
        {children}
        </body>
    </html>
  )
}
