
import './globals.css'
export const dynamic='auto'


export const metadata = {
  title: "Bunny's Bakery Payment",
  description: 'Generated by create next app',
}

export default function PaymentLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
       
       <html lang="en">
       <body className='h-screen bg-gradient-to-tr text-center from-orange-400 via-orange-900 to-orange-800'>
        <div className=" text-3xl text-white font-semibold">We only accept cash on delivery</div>
         {children}
       </body>
     </html>
  )
}
