
import Image from 'next/image'
import './globals.css'
import Link from 'next/link'
import CartCount from '../(components)/Cart/components/cartCount'
import Providers from '../(components)/Cart/Provider'
export const dynamic='auto'


export const metadata = {
  title: "Bunny's Bakery Payment",
  description: 'Generated by create next app',
}

export default function PaymentLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
       <Providers>
       <html lang="en">
       <body className='h-screen bg-gradient-to-tr text-center from-orange-400 via-orange-900 to-orange-800'>
          <div className=" text-3xl text-white font-semibold pb-5">We also accept cash on delivery</div>
          <div className=' flex flex-col place-items-start'> 
          
          <Link href='/Cart/'><Image className='' src={'/cart.svg'} width={100} height={100} alt='cart'/></Link>
          </div>
         {children}
       </body>
     </html>
     </Providers>
  )
}
