'use client'
import './globals.css'
export const dynamic='auto'


export const metadata = {
  title: "Bunny's Bakery Payment",
  description: 'Generated by create next app',
}

export default function PaymentLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
       
       <html lang="en">
       <body className='h-screen bg-gradient-to-tr from-orange-400 via-orange-900 to-orange-800'>
         {children}
       </body>
     </html>
  )
}
