import './globals.css'
import { Inter } from 'next/font/google'
import Header from './Header'
import Footer from './Footer'
import './p.css'
import { client } from '@/sanity/lib/client'
import { CartProvider } from './Cart/cartContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Bunny's Bakery",
  description: 'Generated by create next app',
}

async function getBunnyBakery(){
  const {categories}=(await client.fetch(`*[_type=="BunnyBakery"][0]{categories}`));
  return categories
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const categories=await getBunnyBakery()
  //console.log(categories)
  
  return (
      <CartProvider>
      <html lang="en">
      <body className=" bg-fixed bg-contain bg-[url('/background.jpg')] backdrop-blur-sm backdrop-opacity-60" >
       <Header categories={categories} />
        {children}
       <Footer/>
      </body>
    </html>
    </CartProvider>
  )
}
